version: "3"

services:
    auth_db:
        image: postgres:14-alpine
        container_name: hw3_auth_db
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=hw3_auth_db
        ports:
          - "5432:5432"
    authorization:
        build: ./authorization
        ports:
            - "8008:8008"
        stdin_open: true
        tty: true 
        depends_on:
            - auth_db
    billing_db:
        image: postgres:14-alpine
        container_name: hw3_billing_db
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=hw3_billing_db
        ports:
          - "5433:5432"
    billing:
        build: ./billing
        ports:
            - "8001:8001"
        stdin_open: true
        tty: true 
        depends_on:
            - billing_db
    orders_db:
        image: postgres:14-alpine
        container_name: hw3_orders_db
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=hw3_orders_db
        ports:
          - "5434:5432"
    orders_service:
        build: ./orders_service
        ports:
            - "8002:8002"
        stdin_open: true
        tty: true 
        depends_on:
            - orders_db