import requests

response = requests.post('http://127.0.0.1:8008/sign_up', data={"username": "alesia", "password": "password"})
print(response.json())
token = response.json()["access_token"]
response = requests.post('http://127.0.0.1:8001/user?token=' + token)
print(response.json())
response = requests.post('http://127.0.0.1:8002/user?token=' + token)
print(response.json())
response = requests.put('http://127.0.0.1:8001/put_money?token=' + token + '&money=50')
print(response.json())
response = requests.get('http://127.0.0.1:8001/check_balance?token=' + token)
print(response.json())
response = requests.post('http://127.0.0.1:8002/user/' + token + '/order', json={"title": "apple", "description": "fruit", "price": 40}, headers = {'Content-Type': 'application/json'})
print(response.json())
response = requests.get('http://127.0.0.1:8001/check_balance?token=' + token)
print(response.json())
response = requests.get('http://127.0.0.1:8002/orders/' + token)
print(response.json())
response = requests.post('http://127.0.0.1:8002/user/' + token + '/order', json={"title": "peach", "description": "fruit", "price": 20})
print(response.json())
response = requests.get('http://127.0.0.1:8002/orders/' + token)
print(response.json())
response = requests.get('http://127.0.0.1:8001/check_balance?token=' + token)
print(response.json())
